[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv
lib_deps = 
    h2zero/NimBLE-Arduino@~1.4.1
    lemmingDev/ESP32-BLE-Gamepad@^0.5.4
    adafruit/Adafruit SSD1306@^2.5.9
    adafruit/Adafruit GFX Library@^1.11.9
    sparkfun/SparkFun MAX1704x Fuel Gauge Arduino Library@^1.0.4